version: '3'
services:
  db:
    container_name: postgres_database
    image: "postgres:latest"
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: finances
    volumes:
        - ./pgdata:/var/lib/postgressql/data
    ports:
      - "5431:5432"
    
   
    
  app:
    container_name: finances-api
    restart: always
    build: .
    ports:
      - "8002:8002"
    environment:
        POSTGRES_PORT: 5432
        HOST: db
        PORT: 8002
  


    depends_on:
      - db
      

#       PORT: 8002

# HOST: localhost

# POSTGRES_PORT: 5431